// <auto-generated />
using System;
using AI4CUAV1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AI4CUAV.Migrations
{
    [DbContext(typeof(AI4CUAVDbContext))]
    [Migration("20251021232951_file_url")]
    partial class file_url
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ai4cuav.Models.Dataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnnotationType")
                        .HasColumnType("int");

                    b.Property<string>("Commentss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DatasetSizeMB")
                        .HasColumnType("bigint");

                    b.Property<string>("Datasource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrameRate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfSamples")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectPartner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.Property<double>("TestingSize")
                        .HasColumnType("float");

                    b.Property<double>("TrainingSize")
                        .HasColumnType("float");

                    b.Property<double>("ValidationSize")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("ai4cuav.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnnotationFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomModelNeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataFusionMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataModality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatasetURL")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("DetectionTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("DroneTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Enviroment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("FixedWingClasses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAnnotationType")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("HybridVTOLClasses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDatasetVerified")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("MultiRotorClasses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProvideOwnDataset")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("RecognitionMethods")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecognitionType")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresTracking")
                        .HasColumnType("bit");

                    b.Property<string>("Specifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrgencyLevel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ai4cuav.Models.OrderDatasetProof", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("OrderDatasetProofs");
                });

            modelBuilder.Entity("ai4cuav.Models.OrderDatasetProof", b =>
                {
                    b.HasOne("ai4cuav.Models.Order", "Order")
                        .WithOne()
                        .HasForeignKey("ai4cuav.Models.OrderDatasetProof", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
